### PR TITLE
Source code edits for building on newer Macs

### PR DESCRIPTION
**Pull request by PythonBlue**
This pull request does not have to be implemented fully, by any means, given I had to remove and change some code around, but this is a modified version of the TDD source made to be able to build on x64 Macs.

UPDATE: with my latest commit, the builds should now be fully functional other than a crash warning when quitting.

Major changes:

1. Replaced the 2012.2 FBX SDK with 2014.2. Sadly, this also meant rewriting the MeshLoader code a bit, but I did include a compatibility header from the 2013 SDK to make the edits less cumbersome for Frictional.

2. Due to build errors and inexperience with SDL2 syntax, I ommitted the "remove" functions from the GamepadSDL2 source file, which means I cannot guarantee a gamepad will work with this code.

3. Removed a reference to "GL_RENDERER" in LauncherAppDelegate for the same reasons as the prior difference. Fortunately, the launcher seems to operate fine despite this.

To build on Catalina using this source:
1. Configure using CMake. After that happens, make sure you specify the included Steam.txt (in the now-unzipped dependencies folder) for the Steam library, assuming you don't already have it, or else you can't generate, and also make sure you check "Is_Apple_64". Reconfigure and then generate. I recommend an Xcode project over makefiles in case of issues.

2. In XCode, make sure all of the builds are set to x86_64 architectures only, a 10.7 or later deployment target (I used 10.8), and libc++ for C++ compiling (NOT libstdc++ due to type errors when building).

3. Build, and test, making sure you add the Frameworks folder to the newly compiled apps before running.

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Can you remove ``.DS_Store`` and ignore them?

**Comment by PythonBlue** [comment]
> Can you remove `.DS_Store` and add the mto the git ignore?

Thanks for the feedback. Sadly, while I'll try, I'm not certain how I can effectively remove those files. Again, I'm a Mac user, and DS_Store files seem to automatically be created in directories per the OS.

**Comment by SuperSandro2000** [comment]
> Thanks for the feedback. Sadly, while I'll try, I'm not certain how I can effectively remove those files. Again, I'm a Mac user, and DS_Store files seem to automatically be created in directories per the OS.

Add ``.DS_Store`` to the ``.gitignore`` and you can remove them with ``rm -f **/.DS_Store``.

**Comment by ell1e** [comment]
This seems to do things that impact other platforms like turn sound threading off, and all those commented out things. Why not use `#ifdef __APPLE__` or similar at least, so that it doesn't impact other platforms? It seems hard to ever see this merged if it needlessly degrades functionality on other platforms just to make macOS somehow work

**Comment by PythonBlue** [comment]
Thank you for the feedback. I can see about adding those conditional statements insofar as the actual code, though I question the purpose of the sound threading since all it did for me is skip dialog for the Mac builds: no difference on my PC-based tests.

As for the dependencies, that was intentional that I extracted them because I did change some of those files and wanted to save other contributors some effort of trying to figure out which files inside the zip I had changed.

**Comment by ell1e** [comment]
Ok but if you changed them, then you definitely shouldn't put them where they are right now IMHO because again it will affect other platforms. I'm not sure if zip is the best way either, maybe there needs to be split path in `dependencies/` for each platform but that could also quite bloat the repo. In any case, it doesn't really make sense IMHO to put it in the shared dependency space but then change it for macOS builds only

**Comment by PythonBlue** [comment]
At the very least, it doesn't mess with PC builds, judging from my latest commit: the only dependency files I changed that were irrelevant to the FBX SDK were the Mac-specific libraries for Angelscript. Thank you for reminding me to update the included FBX SDK library for Linux, though.

**Pull request closed without merging**
