### PR TITLE
Linux buildfixes

### PR DESCRIPTION
**Pull request by flibitijibibo**
The following series of patches are quick buildfixes for Linux. For the most part they're harmless, but there are two issues of note:

- While this allows the `Amnesia`/`AmnesiaDemo`/`Launcher` targets to be built, the dev tools will still not build - this is also true for Windows as well though. Until we have the `tests/` directory for SimpleCamera, there's not much we can do about that. EDIT: Directory was added, all targets link now!
- The dependencies.zip does not have valid symlinks, so the linker will still bail when building the final executable. This is easy enough to fix locally by rebuilding them, but it may be a moot point when builds start using system libraries anyhow.

### CODE REVIEW

**Comment by ericonr** [comment]
@flibitijibibo I was thinking of trying to use https://gitlab.com/Mr_Goldberg/goldberg_emulator in place of Steamworks. Do you know if that's possible?

**Comment by flibitijibibo** [comment]
It's probably functional, but I believe the Steamworks code has been stripped out anyway (which is probably the right thing to do) so it would only fix the link process. I think it was just used for achievements anyway so it's probably not a huge deal...

**Comment by coolreader18** [comment]
I get a weird error while linking to the vorbis lib:
```
/usr/bin/ld:/home/coolreader18/AmnesiaTheDarkDescent/HPL2/dependencies/lib/linux/lib64/libvorbisfile.so: file format not recognized; treating as linker script
/usr/bin/ld:/home/coolreader18/AmnesiaTheDarkDescent/HPL2/dependencies/lib/linux/lib64/libvorbisfile.so:1: syntax error
```
`HPL2/dependencies/lib/linux/lib64/libvorbisfile.so` just has this inside:
```
link libvorbisfile.so.3.3.5
```
and `HPL2/dependencies/lib/linux/lib64/libvorbisfile.so.3.3.5` is a valid so file. I'm not to familiar with linker scripts, is that a legitimate error or something with my setup? I've got GNU ld 2.35 on arch linux.

**Comment by fennecdjay** [comment]
I have a similar error as @coolreader18, also on arch.

**Comment by k0pernicus** [comment]
Got the same error as @coolreader18.  
I first tried to link myself the `libvorbisfile.so.3.3.5` to `libvorbisfile.so` but got linker issues (`skipping incompatible <LOCAL_PATH>libvorbisfile.so when searching for -lvorbisfile`) at the end...

Same for vorbis, ogg, openal, ...

**Comment by flibitijibibo** [comment]
Per the OP:

>The dependencies.zip does not have valid symlinks, so the linker will still bail when building the final executable. This is easy enough to fix locally by rebuilding them, but it may be a moot point when builds start using system libraries anyhow.

The .so files will be labeled as `ASCII text` when you check them with `file`, those are the links that need to be rebuilt.

**Comment by k0pernicus** [comment]
After rebuilding the links I have this: `/usr/bin/ld: <LOCAL_PATH>/libvorbisfile.so: error adding symbols: file in wrong format`.

I suppose this is a build architecture issue, right? :thinking:

**Comment by fennecdjay** [comment]
Any hints at how to rebuild dependencies?

**Comment by k0pernicus** [comment]
@fennecdjay I suppose you have to rebuild only the links.

So, for `<LOCAL_PATH>/libvorbisfile.so` you can do this:

```
cat <LOCAL_PATH>/libvorbisfile.so # note the linked .so (LINKED_SO) here, should be libvorbisfile.so.3.3.5
rm <LOCAL_PATH>/libvorbisfile.so
ln -s <LOCAL_PATH>/<LINKED_SO> <LOCAL_PATH>/libvorbisfile.so
```
and do this for all of the .so files...

**Comment by robalni** [comment]
Here is a quick way to recreate the links. Run it from the directory the links are in.

```
for f in `file * | grep ASCII | cut -d: -f1`; do ln -fs `cut -d' ' -f2 $f` $f; done
```

**Comment by k0pernicus** [comment]
Yep, I did it, for got an issue with `libGLEW.a(glew.o)`: `/usr/bin/ld: /home/antonin/Devel/AmnesiaTheDarkDescent/HPL2/dependencies/lib/linux/lib/libGLEW.a(glew.o): relocation R_X86_64_32S against '.rodata' can not be used when making a PIE object; recompile with -fPIE`

I will try to find the right place to enable ASLR then :+1:

**Comment by coolreader18** [comment]
@robalni that worked after I ran it in `lib/linux/lib64` and `lib/linux/lib`, thanks! Now I've got the same error that k0pernicus does

**Comment by fennecdjay** [comment]
I still have problems with the libs, also I have
```
/media/DOC3/Jeux/AmnesiaTheDarkDescent/HPL2/tools/modelview/ModelView.cpp:22:10: erreur fatale: ../../tests/Common/SimpleCamera.h : Aucun fichier ou dossier de ce type
   22 | #include "../../tests/Common/SimpleCamera.h"
```

which I have no clue how to fix.

**Comment by flibitijibibo** [comment]
Per the OP (again):

>While this allows the Amnesia/AmnesiaDemo/Launcher targets to be built, the dev tools will still not build - this is also true for Windows as well though. Until we have the tests/ directory for SimpleCamera, there's not much we can do about that.

To fix pretty much all of the linker issues you will all most likely want to focus on removing the use of local dependencies and linking to the system libraries instead.

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
In between I tried to build the project on my Mac. In each folder everything ends like this:

```
Users-Mac-Pro:core user$ cmake .
CMake Warning (dev) at CMakeLists.txt:21 (set):
  Cannot set "DEP_LIB_DIR": current scope has no parent.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:22 (set):
  Cannot set "DEP_INCLUDE_DIR": current scope has no parent.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at CMakeLists.txt:347 (add_subdirectory):
  add_subdirectory given source "../tests" which is not an existing
  directory.


CMake Warning (dev) at /opt/local/share/cmake-3.18/Modules/BundleUtilities.cmake:233 (message):
  Policy CMP0080 is not set: BundleUtilities cannot be included at configure
  time.  Run "cmake --help-policy CMP0080" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

Call Stack (most recent call first):
  /opt/local/share/cmake-3.18/Modules/BundleUtilities.cmake:242 (_warn_cmp0080)
  CMakeLists.txt:305 (INCLUDE)
  /Users/user/AmnesiaTheDarkDescent/HPL2/tools/CMakeLists.txt:26 (PostBuildMacBundle)
  /Users/user/AmnesiaTheDarkDescent/HPL2/tools/editors/CMakeLists.txt:123 (AddToolTarget)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:306 (GET_TARGET_PROPERTY):
  Policy CMP0026 is not set: Disallow use of the LOCATION target property.
  Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The LOCATION property should not be read from target "LevelEditor".  Use
  the target name directly with add_custom_command, or use the generator
  expression $<TARGET_FILE>, as appropriate.

Call Stack (most recent call first):
  /Users/user/AmnesiaTheDarkDescent/HPL2/tools/CMakeLists.txt:26 (PostBuildMacBundle)
  /Users/user/AmnesiaTheDarkDescent/HPL2/tools/editors/CMakeLists.txt:123 (AddToolTarget)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /opt/local/share/cmake-3.18/Modules/BundleUtilities.cmake:233 (message):
  Policy CMP0080 is not set: BundleUtilities cannot be included at configure
  time.  Run "cmake --help-policy CMP0080" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

Call Stack (most recent call first):
  /opt/local/share/cmake-3.18/Modules/BundleUtilities.cmake:242 (_warn_cmp0080)
  CMakeLists.txt:305 (INCLUDE)
  /Users/user/AmnesiaTheDarkDescent/HPL2/tools/CMakeLists.txt:26 (PostBuildMacBundle)
  /Users/user/AmnesiaTheDarkDescent/HPL2/tools/editors/CMakeLists.txt:241 (AddToolTarget)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:306 (GET_TARGET_PROPERTY):
  Policy CMP0026 is not set: Disallow use of the LOCATION target property.
  Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The LOCATION property should not be read from target "ModelEditor".  Use
  the target name directly with add_custom_command, or use the generator
  expression $<TARGET_FILE>, as appropriate.

Call Stack (most recent call first):
  /Users/user/AmnesiaTheDarkDescent/HPL2/tools/CMakeLists.txt:26 (PostBuildMacBundle)
  /Users/user/AmnesiaTheDarkDescent/HPL2/tools/editors/CMakeLists.txt:241 (AddToolTarget)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /opt/local/share/cmake-3.18/Modules/BundleUtilities.cmake:233 (message):
  Policy CMP0080 is not set: BundleUtilities cannot be included at configure
  time.  Run "cmake --help-policy CMP0080" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

Call Stack (most recent call first):
  /opt/local/share/cmake-3.18/Modules/BundleUtilities.cmake:242 (_warn_cmp0080)
  CMakeLists.txt:305 (INCLUDE)
  /Users/user/AmnesiaTheDarkDescent/HPL2/tools/CMakeLists.txt:26 (PostBuildMacBundle)
  /Users/user/AmnesiaTheDarkDescent/HPL2/tools/editors/CMakeLists.txt:313 (AddToolTarget)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:306 (GET_TARGET_PROPERTY):
  Policy CMP0026 is not set: Disallow use of the LOCATION target property.
  Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The LOCATION property should not be read from target "ParticleEditor".  Use
  the target name directly with add_custom_command, or use the generator
  expression $<TARGET_FILE>, as appropriate.

Call Stack (most recent call first):
  /Users/user/AmnesiaTheDarkDescent/HPL2/tools/CMakeLists.txt:26 (PostBuildMacBundle)
  /Users/user/AmnesiaTheDarkDescent/HPL2/tools/editors/CMakeLists.txt:313 (AddToolTarget)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /opt/local/share/cmake-3.18/Modules/BundleUtilities.cmake:233 (message):
  Policy CMP0080 is not set: BundleUtilities cannot be included at configure
  time.  Run "cmake --help-policy CMP0080" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

Call Stack (most recent call first):
  /opt/local/share/cmake-3.18/Modules/BundleUtilities.cmake:242 (_warn_cmp0080)
  CMakeLists.txt:305 (INCLUDE)
  /Users/user/AmnesiaTheDarkDescent/HPL2/tools/CMakeLists.txt:26 (PostBuildMacBundle)
  /Users/user/AmnesiaTheDarkDescent/HPL2/tools/editors/CMakeLists.txt:380 (AddToolTarget)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:306 (GET_TARGET_PROPERTY):
  Policy CMP0026 is not set: Disallow use of the LOCATION target property.
  Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The LOCATION property should not be read from target "MaterialEditor".  Use
  the target name directly with add_custom_command, or use the generator
  expression $<TARGET_FILE>, as appropriate.

Call Stack (most recent call first):
  /Users/user/AmnesiaTheDarkDescent/HPL2/tools/CMakeLists.txt:26 (PostBuildMacBundle)
  /Users/user/AmnesiaTheDarkDescent/HPL2/tools/editors/CMakeLists.txt:380 (AddToolTarget)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /opt/local/share/cmake-3.18/Modules/BundleUtilities.cmake:233 (message):
  Policy CMP0080 is not set: BundleUtilities cannot be included at configure
  time.  Run "cmake --help-policy CMP0080" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

Call Stack (most recent call first):
  /opt/local/share/cmake-3.18/Modules/BundleUtilities.cmake:242 (_warn_cmp0080)
  CMakeLists.txt:305 (INCLUDE)
  /Users/user/AmnesiaTheDarkDescent/HPL2/tools/CMakeLists.txt:26 (PostBuildMacBundle)
  /Users/user/AmnesiaTheDarkDescent/HPL2/tools/CMakeLists.txt:45 (AddToolTarget)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:306 (GET_TARGET_PROPERTY):
  Policy CMP0026 is not set: Disallow use of the LOCATION target property.
  Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The LOCATION property should not be read from target "MapViewer".  Use the
  target name directly with add_custom_command, or use the generator
  expression $<TARGET_FILE>, as appropriate.

Call Stack (most recent call first):
  /Users/user/AmnesiaTheDarkDescent/HPL2/tools/CMakeLists.txt:26 (PostBuildMacBundle)
  /Users/user/AmnesiaTheDarkDescent/HPL2/tools/CMakeLists.txt:45 (AddToolTarget)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /opt/local/share/cmake-3.18/Modules/BundleUtilities.cmake:233 (message):
  Policy CMP0080 is not set: BundleUtilities cannot be included at configure
  time.  Run "cmake --help-policy CMP0080" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

Call Stack (most recent call first):
  /opt/local/share/cmake-3.18/Modules/BundleUtilities.cmake:242 (_warn_cmp0080)
  CMakeLists.txt:305 (INCLUDE)
  /Users/user/AmnesiaTheDarkDescent/HPL2/tools/CMakeLists.txt:26 (PostBuildMacBundle)
  /Users/user/AmnesiaTheDarkDescent/HPL2/tools/CMakeLists.txt:52 (AddToolTarget)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:306 (GET_TARGET_PROPERTY):
  Policy CMP0026 is not set: Disallow use of the LOCATION target property.
  Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The LOCATION property should not be read from target "ModelViewer".  Use
  the target name directly with add_custom_command, or use the generator
  expression $<TARGET_FILE>, as appropriate.

Call Stack (most recent call first):
  /Users/user/AmnesiaTheDarkDescent/HPL2/tools/CMakeLists.txt:26 (PostBuildMacBundle)
  /Users/user/AmnesiaTheDarkDescent/HPL2/tools/CMakeLists.txt:52 (AddToolTarget)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
See also "/Users/user/AmnesiaTheDarkDescent/HPL2/core/CMakeFiles/CMakeOutput.log".
```

Looks like there is need enough work to be done to make the project compatible with the latest version of CMake and dependencies.

**Comment by robalni** [comment]
@aeiouaeiouaeiouaeiouaeiouaeiou I get similar error as the first one you got when I try cmake in the core directory. Try instead the directory amnesia/src.

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
@robalni now stuck on Launcher_Prefix file.

```
CMake Error at /Users/user/AmnesiaTheDarkDescent/HPL2/core/CMakeLists.txt:306 (GET_TARGET_PROPERTY):
  Cannot find source file:

    Launcher_Prefix.pch

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx
Call Stack (most recent call first):
  launcher-macosx/CMakeLists.txt:105 (PostBuildMacBundle)
```

**Comment by flibitijibibo** [comment]
If patch review isn't being done there may be a better place for discussion - there isn't a place on the forum for the Amnesia source yet but it may be worth bringing up: https://www.frictionalgames.com/forum/

Other issues unrelated to this patchset should be filed separately.

**Comment by Mudbill** [comment]
I've had a fair few compile errors complain about:

    relocation R_X86_64_32S against .rodata can not be used when making a PIE object; recompile with -fPIE

The fix I've used to progress past it is to add the `-no-pie` compile flag, *not* the `-fPIE` flag, inside the cmake files.

**Comment by juliosueiras** [comment]
yea, also stuck at needing the `SimpleCamera.h` as well, this is what I currently have in nix for this

```nix
with import <nixpkgs> {};

stdenv.mkDerivation {
  name = "AmnesiaTheDarkDescent";

  src = fetchFromGitHub {
    repo = "AmnesiaTheDarkDescent";
    owner = "FrictionalGames";
    rev = "master";
    sha256 = "yaym9rOb7/FjW2TESJdC4v7yknn+20zaC7T4kHqyKSY=";
  };

  buildInputs = [ cmake libGL.dev libGLU.dev xorg.libX11.dev ];

  patches = [
    (fetchpatch {
      url = "https://github.com/FrictionalGames/AmnesiaTheDarkDescent/pull/2.patch";
      sha256 = "jElow6Str+sPJdH3deCzaAa4uraZYTz4wGyJyDOi/GA=";
    })
  ];

  postPatch = ''
    pushd .
    cd HPL2
    ${unzip}/bin/unzip dependencies.zip -d dependencies
    popd

    sed -i 's;/usr/bin/perl;${perl}/bin/perl;g' ./HPL2/core/buildcounter.pl
  '';

  cmakeDir = "../amnesia/src";
}
```

**Comment by juliosueiras** [comment]
actually never mind, SimpleCamera.h look like is at https://github.com/FrictionalGames/HPL1Engine/tree/master/tests/Common

**Comment by juliosueiras** [comment]
seem to be the same name but different internal implementation , so not really usable

**Comment by coolreader18** [comment]
Yup, I tried that as well, it seems like an older version, especially since that's hpl1 and this is hpl2

**Comment by juliosueiras** [comment]
oh well, I guess is time to wait until tests folder get uploaded

**Comment by frictional-edvin** [comment]
Hey
I just added the files for simple camera!

Give it a go and let me know if there's anything else missing!

**Comment by brynet** [comment]
> let me know if there's anything else missing!

The sources for the prebuilt dependencies (w/ any modifications) would be helpful, for example the version of Newton (2.0) used by HPL2 appears to be unavailable online, it's unclear if Amnesia will compile with later versions of the API (3 & 4) found [here](https://github.com/MADEAPPS/newton-dynamics).

It is also not currently possible to build Amnesia or HPL2 entirely from source, without any prebuilt dependencies until the (singular?) proprietary component `fbxsdk-2012.2-static` can be replaced.

**Comment by flibitijibibo** [comment]
Force-pushed to match the latest revision. It looks like a CMake file was missing but I'm assuming there's a ton of custom stuff in there, so I added a quick file to cover the two new files, and everything links successfully now.

This should be good to merge again!

**Comment by sthilaid** [comment]
> I've had a fair few compile errors complain about:
> 
> ```
> relocation R_X86_64_32S against .rodata can not be used when making a PIE object; recompile with -fPIE
> ```
> 
> The fix I've used to progress past it is to add the `-no-pie` compile flag, _not_ the `-fPIE` flag, inside the cmake files.

What's the best way to do that? I'm not very familiar with cmake... Thanks!

**Comment by Mudbill** [comment]
@sthilaid I have a full video on it [here](https://www.youtube.com/watch?v=sW9aDVUPCUM&lc=UgzTLNhlzgmIR8_Owa54AaABAg), but basically you edit the CMakeLists.txt file in several locations, particularly in `amnesia/src` and `HPL2/core`. At the bottom of the file, add `set(CMAKE_CXX_FLAGS "-fpermissive -no-pie")` (fpermissive is mentioned earlier in this thread).

**Comment by ericwomer** [comment]
> Per the OP:
> 
> > The dependencies.zip does not have valid symlinks, so the linker will still bail when building the final executable. This is easy enough to fix locally by rebuilding them, but it may be a moot point when builds start using system libraries anyhow.
> 
> The .so files will be labeled as `ASCII text` when you check them with `file`, those are the links that need to be rebuilt.

The problem here isn't the broken shared links but even when building on 64bit it still tries to link to the 32bit libraries in the HPL2/dependencies/lib/linux/lib folder and not the HPL2/dependencies/lib/linux/lib64 folder like it should.

**Comment by Mudbill** [comment]
> The problem here isn't the broken shared links but even when building on 64bit it still tries to link to the 32bit libraries in the HPL2/dependencies/lib/linux/lib folder and not the HPL2/dependencies/lib/linux/lib64 folder like it should.

I haven't had that happen to me. My system has picked the 64-bit libraries in lib64 each time.

**Comment by sthilaid** [comment]
> @sthilaid I have a full video on it [here](https://www.youtube.com/watch?v=sW9aDVUPCUM&lc=UgzTLNhlzgmIR8_Owa54AaABAg), but basically you edit the CMakeLists.txt file in several locations, particularly in `amnesia/src` and `HPL2/core`. At the bottom of the file, add `set(CMAKE_CXX_FLAGS "-fpermissive -no-pie")` (fpermissive is mentioned earlier in this thread).

Thank you very much. This worked perfectly. I already had fixed the errors mentionned that are avoided by the permissive flag, but didn't know how to tell g++ to use -no-pie :). I only modified the root CMakeLists.txt file and the HPL2/core/CMakeLists.txt files and it was sufficient. (I'm working on the a machine for pigs repo though).

Cheers!

**Comment by flibitijibibo** [comment]
Looks like a force-push blew this apart - should I rebase and resubmit?

**Comment by ericwomer** [comment]
Yeah, it could still help, don't know why they closed this.

**Comment by brynet** [comment]
It looks like commit history was lost as of 4 hours ago, @frictional-edvin, what happened here? Was this an accident?

**Comment by Mudbill** [comment]
It was intentional. I believe it was to remove the FBX SDK due to licensing restrictions, so now that has to be added separately.

**Comment by ericwomer** [comment]
There have been tons of projects that have to remove licensed material that didn't nuke their entire history.

**Comment by Mudbill** [comment]
In that case I'm not sure why the history was removed. You can ask Edvin. He's most likely to reply in the Discord server.

**Pull request closed without merging**
